name: Reusable Deploy
# this allows this workflow to be called from other workflows
on: 
  workflow_call:
    # args.
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: true
        default: dist
        type: string
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."
